name: CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.3'  
    - name: Install dependencies
      run: |
        pip install pycryptodome pytest

    - name: Compile C code
      run: |
        gcc -shared -o rijndael.dll rijndael.c  # Compile the DLL

    - name: Run tests
      run: |
        python -m pytest -v